apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: democratic-csi-truenas-iscsi-nvme
  namespace: {{ .Values.argoCDNamespace }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: democratic-csi

  source:
    repoURL: https://democratic-csi.github.io/charts/
    chart: democratic-csi
    targetRevision: 0.15.1

    helm:
      valuesObject:
        driver:
          existingConfigSecret: truenas-iscsi-nvme-driver-config
          config:
            driver: truenas-iscsi

        csiDriver:
          name: "org.democratic-csi.truenas-iscsi-nvme"

        storageClasses:
          - name: truenas-iscsi-nvme
            defaultClass: false
            reclaimPolicy: Delete
            volumeBindingMode: Immediate
            allowVolumeExpansion: true
            parameters:
              fsType: ext4
              detachedVolumesFromSnapshots: "false"
            mountOptions: []
            secrets:
              provisioner-secret:
              controller-publish-secret:
              node-stage-secret:
              node-publish-secret:
              controller-expand-secret:

        node:
          hostPID: true
          driver:
            extraEnv:
              - name: ISCSIADM_HOST_STRATEGY
                value: nsenter
              - name: ISCSIADM_HOST_PATH
                value: /usr/local/sbin/iscsiadm
            iscsiDirHostPath: /var/iscsi
            iscsiDirHostPathType: ""

        volumeSnapshotClasses:
          - name: truenas-iscsi-nvme
            parameters:
              detachedSnapshots: "true"

  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Release.Namespace }}

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
