apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: longhorn

  sources:
    - repoURL: {{ .Values.repository.url }}
      targetRevision: {{ .Values.repository.targetRevision }}
      path: argo/longhorn

    - repoURL: https://oauth2-proxy.github.io/manifests
      targetRevision: 8.1.1
      chart: oauth2-proxy

      helm:
        valuesObject:
          config:
            existingSecret: longhorn-oidc-secrets

            configFile: |-
              email_domains = ["*"]
              provider = "keycloak-oidc"
              oidc_issuer_url = "https://id.d3adb5.ca/realms/core"
              redirect_url = "https://longhorn.d3adb5.ca/oauth2/callback"
              code_challenge_method = "S256"

          ingress:
            enabled: true
            className: nginx
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt
            hosts:
              - "longhorn.d3adb5.ca"
            path: /oauth2
            tls:
              - hosts:
                  - "longhorn.d3adb5.ca"
                secretName: longhorn-ui-tls

    - repoURL: https://charts.longhorn.io
      targetRevision: 1.7.0
      chart: longhorn

      helm:
        valuesObject:
          preUpgradeChecker:
            jobEnabled: false
          persistence:
            defaultClassReplicaCount: 3
            migratable: true
          ingress:
            enabled: true
            ingressClassName: nginx
            host: longhorn.d3adb5.ca
            tls: true
            tlsSecret: longhorn-ui-tls
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt
              {{- toYaml .Values.ingress.oauth2-proxy-annotations | nindent 14 }}
          networkPolicies:
            enabled: true

  destination:
    namespace: {{ .Values.longhorn.namespace }}
    server: https://kubernetes.default.svc

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
