apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: longhorn

  sources:
    - repoURL: {{ .Values.repository.url }}
      targetRevision: {{ .Values.repository.targetRevision }}
      path: argo/longhorn

    - repoURL: https://charts.longhorn.io
      targetRevision: 1.7.0
      chart: longhorn

      helm:
        valuesObject:
          preUpgradeChecker:
            jobEnabled: false
          persistence:
            defaultClassReplicaCount: 3
            migratable: true
          ingress:
            enabled: false
          networkPolicies:
            enabled: true

  destination:
    namespace: {{ .Values.longhorn.namespace }}
    server: https://kubernetes.default.svc

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
