apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: longhorn

  sources:
    - repoURL: {{ .Values.repository.homelab.url }}
      targetRevision: {{ .Values.repository.homelab.targetRevision }}
      path: argo/longhorn

    - repoURL: https://oauth2-proxy.github.io/manifests
      targetRevision: 10.7.0
      chart: oauth2-proxy

      helm:
        valuesObject:
          config:
            existingSecret: longhorn-oidc-secrets

            configFile: |-
              email_domains = ["*"]
              provider = "keycloak-oidc"
              oidc_issuer_url = "https://id.d3adb5.ca/realms/core"
              redirect_url = "https://longhorn.d3adb5.ca/oauth2/callback"
              code_challenge_method = "S256"
              allowed_groups = ["/Longhorn"]
              upstreams = [ "static://202" ]
              reverse_proxy = true
              skip_provider_button = true

          metrics:
            serviceMonitor:
              enabled: true

          ingress:
            enabled: true
            className: traefik
            hosts:
              - "longhorn.d3adb5.ca"
            path: /oauth2
            tls:
              - hosts:
                  - "longhorn.d3adb5.ca"
                secretName: longhorn-ui-tls

    - repoURL: https://charts.longhorn.io
      targetRevision: 1.12.0
      chart: longhorn

      helm:
        valuesObject:
          preUpgradeChecker:
            jobEnabled: false
          persistence:
            defaultClassReplicaCount: 3
            defaultDataLocality: best-effort
            migratable: true
          ingress:
            enabled: true
            ingressClassName: traefik
            host: longhorn.d3adb5.ca
            tls: true
            tlsSecret: longhorn-ui-tls
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt
              traefik.ingress.kubernetes.io/router.middlewares: "{{ .Values.longhorn.namespace }}-longhorn-oauth2-proxy@kubernetescrd"
          networkPolicies:
            enabled: true
          metrics:
            serviceMonitor:
              enabled: true

  destination:
    namespace: {{ .Values.longhorn.namespace }}
    server: https://kubernetes.default.svc

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
