apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-utils
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: cluster-utils

  source:
    repoURL: {{ .Values.repository.url }}
    targetRevision: {{ .Values.repository.targetRevision }}
    path: argo/cluster-utils

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
