apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: metallb

  sources:
    - repoURL: https://metallb.github.io/metallb
      targetRevision: 0.15.2
      chart: metallb
    - repoURL: {{ .Values.repository.homelab.url }}
      targetRevision: {{ .Values.repository.homelab.targetRevision }}
      path: argo/metallb

  destination:
    namespace: {{ .Values.metallb.namespace }}
    server: https://kubernetes.default.svc

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

  ignoreDifferences:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: bgppeers.metallb.io
      jsonPointers:
        - /spec/conversion/webhook/clientConfig/caBundle
