customization:
  extraKernelArgs:
    - -selinux
    - -init_on_alloc
    - talos.auditd.disabled=1
  systemExtensions:
    officialExtensions:
      - siderolabs/i915-ucode
      - siderolabs/intel-ucode
      - siderolabs/iscsi-tools
