apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: beets
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: media

  sources:
    - repoURL: {{ .Values.repository.homelab.url }}
      targetRevision: {{ .Values.repository.homelab.targetRevision }}
      path: argo/media/beets

    - repoURL: https://oauth2-proxy.github.io/manifests
      targetRevision: 8.5.1
      chart: oauth2-proxy

      helm:
        valuesObject:
          config:
            existingSecret: beets-oidc-secrets

            configFile: |-
              email_domains = ["*"]
              provider = "keycloak-oidc"
              oidc_issuer_url = "https://id.d3adb5.ca/realms/core"
              redirect_url = "https://beets.d3adb5.ca/oauth2/callback"
              code_challenge_method = "S256"
              allowed_groups = ["/Beets"]

          ingress:
            enabled: true
            className: nginx
            annotations:
              {{- toYaml .Values.ingress.oauth2ProxyIngressAnnotations | nindent 14 }}
            hosts:
              - "beets.d3adb5.ca"
            path: /oauth2
            tls:
              - hosts:
                  - "beets.d3adb5.ca"
                secretName: beets-tls

    - repoURL: https://charts.d3adb5.net
      targetRevision: 1.1.0
      chart: stateful

      helm:
        valuesObject:
          replicaCount: 1
          image:
            repository: lscr.io/linuxserver/beets
            tag: "2.5.1@sha256:d591337d1c7bc512b52c8e19a6f881f3095b0bcd4f41b697a3b8f747df6d477d"
            pullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 20m
              memory: 128Mi
            limits:
              memory: 1Gi
          service:
            port: 8337
          ingress:
            enabled: true
            host: beets.d3adb5.ca
            className: nginx
            tls:
              enabled: true
              secretName: beets-tls
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt
              {{- toYaml .Values.ingress.oauth2ProxyAnnotations | nindent 14 }}
          extraEnv:
            - name: TZ
              value: America/Vancouver
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
          extraVolumes:
            - name: music-library
              persistentVolumeClaim:
                claimName: {{ .Values.media.libraries.music.claimName }}
          extraVolumeMounts:
            - name: music-library
              mountPath: /downloads
              subPath: complete
            - name: music-library
              mountPath: /music
              subPath: library
            - name: config
              mountPath: /config
          extraVolumeClaimTemplates:
            - metadata:
                name: config
              spec:
                accessModes: [ "ReadWriteOnce" ]
                storageClassName: longhorn
                resources:
                  requests:
                    storage: 4Gi

  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.media.namespace }}

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
