apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: extra-media-resources
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: media

  source:
    repoURL: {{ .Values.repository.homelab.url }}
    targetRevision: {{ .Values.repository.homelab.targetRevision }}
    path: argo/media/extra-resources

  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.media.namespace }}

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
