apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: navidrome
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: media

  source:
    repoURL: oci.trueforge.org/truecharts
    chart: navidrome
    targetRevision: 22.13.0

    helm:
      valuesObject:
        workload:
          main:
            podSpec:
              containers:
                main:
                  env:
                    ND_MUSICFOLDER: /music
                    ND_PROMETHEUS_ENABLED: "true"
                    ND_ENABLESHARING: "true"

        persistence:
          data:
            enabled: true
            type: pvc
            storageClass: longhorn
            size: 10Gi
          music:
            existingClaim: {{ .Values.media.libraries.music.claimName }}
            subPath: library
            mountPath: /music
            readOnly: true

        ingress:
          main:
            enabled: true
            ingressClassName: nginx
            annotations:
              nginx.ingress.kubernetes.io/configuration-snippet: |
                location /metrics {
                  deny all;
                  return 403;
                }
              cert-manager.io/cluster-issuer: letsencrypt
            hosts:
              - host: navidrome.d3adb5.ca
            tls:
              - hosts:
                  - navidrome.d3adb5.ca
                secretName: navidrome-tls

  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.media.namespace }}

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
