apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: plex-media-server
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: media

  source:
    repoURL: https://raw.githubusercontent.com/plexinc/pms-docker/gh-pages
    targetRevision: 1.1.2
    chart: plex-media-server

    helm:
      valuesObject:
        nodeSelector:
          feature.node.kubernetes.io/gpu.present: "true"
        runtimeClassName: nvidia
        image:
          repository: plexinc/pms-docker
          tag: "1.42.1.10060-4e8b05daf@sha256:4e704a2172129d8a6bc5b05ea201945b329bb6512f48a4e92ed4a4a787c35462"
          pullPolicy: IfNotPresent
        ingress:
          enabled: true
          ingressClassName: nginx
          url: plex.d3adb5.ca
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt
          tls:
            - hosts:
                - plex.d3adb5.ca
              secretName: plex-media-server-tls
        extraEnv:
          # If redeploying, generate a new claim token through https://www.plex.tv/claim/
          PLEX_CLAIM: "claim-qosQGNGbGD4EHHsGMVtg"
          HOSTNAME: Plex
          TZ: America/Vancouver
        extraVolumes:
          - name: movies-library
            persistentVolumeClaim:
              claimName: {{ .Values.media.libraries.movies.claimName }}
          - name: tv-library
            persistentVolumeClaim:
              claimName: {{ .Values.media.libraries.tv.claimName }}
        extraVolumeMounts:
          - name: tv-library
            mountPath: /media/tv
            subPath: library
          - name: movies-library
            mountPath: /media/movies
            subPath: library
        service:
          type: NodePort
          nodePort: 32400
        pms:
          gpu:
            nvidia:
              enabled: true
          storageClassName: longhorn
          configStorage: 10Gi
          resources:
            requests:
              cpu: 2
              memory: 4Gi
            limits:
              memory: 4Gi

  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.media.namespace }}

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
