apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ddclient-credentials
spec:
  encryptedData:
    password: AgCpdpBq/tqg9DFZ+LVNluI5uS4TGMFjlgQ5SkPkrYyPHM3HpnBG56SrVj3Smw6YlhDPikGqIVREyGE4T8ApYIqmCKO0DhFoI77FrEDcq9P1m4SekFFLou8PUNydV6d/Ss8UwPfe0eIpVcHpIYujk7lsBZLgpaYb2tAR0nN8YvVmZDzDFC0XytWm981br5QwcIDpXG5CDj6t0kpfTQSCWpaXKp5tyJ9UCx5eys/yfa8UJyk55QeobQkRrNeT4hlJlErfwNaqqNC5aGz0bOjbr2ucqUkqcy7kXic55yiP5+kuPDo+nWWpf3seuZ/BlUqZ23Jthk4RBA92zX+wrNHNoL2yM1o9Qd8tLiu610aSKOlcjHui3bm6A3CoO+ldxGlRee9RnJzCUeA25+LYgG2c9yEwmvl/QxvxY3L+lA/QDQ3FIKhRCP4wg1lc1vK+HadJxlsZevG17Le+h6VSlO32aK8DZSqnvugV2D8nuDp9OdA1RcokxDPB3C25RIDDpBMbjANPwTz7LJB1iwg93MGQrBmq7uUiILV/k6jlBlrt0VSstKZpTbxUy9ii0Rr0i/xyrU9iF4iyaGPK11bwHe4gVhc6niJLXQxzkOWprVf64Q6tJwLexD7XDOWCISd9RVsoFxJZ8tP3q3YkSCQDa6KC08ExNUUtRslNywbfQNUu2LCxHSxfPnX3sVzDCyUMZ8gu86Y/w7YIAjV95rh0iurxr+LOsB+XVaXb1NocKMOyYjXmXOfAQpniHeSz
