apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-library-music
  finalizers:
    - kubernetes.io/pvc-protection
spec:
  storageClassName: truenas-nfs-hdd
  accessModes: [ ReadWriteMany ]
  resources:
    requests:
      storage: 2Ti

  volumeName: pvc-267acbd6-7a63-48f6-99e0-cec4d6a02e99
