apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-snapshotter
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  sources:
    - repoURL: "https://github.com/kubernetes-csi/external-snapshotter"
      targetRevision: v8.3.0
      path: client/config/crd
    - repoURL: "https://github.com/kubernetes-csi/external-snapshotter"
      targetRevision: v8.3.0
      path: deploy/kubernetes/snapshot-controller

  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
