apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: network-policies
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: network-policies

  source:
    repoURL: {{ .Values.repository.homelab.url }}
    targetRevision: {{ .Values.repository.homelab.targetRevision }}
    path: argo/network-policies

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
