apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  sources:
    - repoURL: {{ .Values.repository.homelab.url }}
      targetRevision: {{ .Values.repository.homelab.targetRevision }}
      path: {{ .Values.repository.homelab.path }}

    - repoURL: {{ .Values.repository.secretlab.url }}
      targetRevision: {{ .Values.repository.secretlab.targetRevision }}
      path: {{ .Values.repository.secretlab.path }}

      helm:
        valuesObject:
          {{- toYaml .Values | nindent 10 }}

  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.argocd.namespace }}

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
