apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mc-router
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: minecraft
  source:
    repoURL: https://itzg.github.io/minecraft-server-charts
    targetRevision: 1.4.1
    chart: mc-router

    helm:
      valuesObject:
        minecraftRouter:
          mappings:
            - port: 25565
              externalHostname: "test.d3adb5.ca"
              host: "192.168.1.237"
            - port: 25565
              externalHostname: "guglets.d3adb5.ca"
              host: "192.168.1.237"
            - port: 25565
              externalHostname: "chudbunnies.d3adb5.ca"
              host: "192.168.1.237"
        services:
          minecraft:
            type: LoadBalancer
            port: 25565
            annotations:
              metallb.universe.tf/allow-shared-ip: {{ .Values.metallb.ipSharingKey }}
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            memory: 64Mi

  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.minecraft.namespace }}

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
