apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mc-router
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: minecraft
  source:
    repoURL: https://itzg.github.io/minecraft-server-charts
    targetRevision: 1.2.5
    chart: mc-router

    helm:
      valuesObject:
        services:
          minecraft:
            type: LoadBalancer
            port: 25565
            annotations:
              metallb.universe.tf/allow-shared-ip: {{ .Values.metallb.ipSharingKey }}
        resources:
          requests:
            cpu: 100m
            memory: 32Mi
          limits:
            cpu: 100m
            memory: 32Mi

  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.minecraft.namespace }}

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
