apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minecraft-gug
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: minecraft
  source:
    repoURL: https://itzg.github.io/minecraft-server-charts
    targetRevision: 5.0.0
    chart: minecraft
    helm:
      valuesObject:
        serviceAnnotations:
          mc-router.itzg.me/externalServerName: "gug.d3adb5.ca"
        workloadAsStatefulSet: true
        strategyType: RollingUpdate
        persistence:
          storageClass: longhorn
          dataDir:
            enabled: true
            Size: 20Gi
        resources:
          requests:
            cpu: 2
            memory: 16Gi
          limits:
            memory: 16Gi
        extraEnv:
          USE_MEOWICE_FLAGS: "true"
        minecraftServer:
          eula: true
          type: FORGE
          downloadModpackUrl: "http://0x0.st/H3s4.3.zip"
          version: "1.12.2"
          difficulty: normal
          whitelist: {{ join "," .Values.minecraft.server.gug.whitelist }}
          ops: {{ join "," .Values.minecraft.server.gug.ops }}
          maxPlayers: 16
          allowNether: true
          announcePlayerAchievements: true
          spawnProtection: 0
          viewDistance: 32
          motd: "Onnie and Beaver, sitting under a tree..."
          icon: "http://0x0.st/K_t4.png"
          rcon:
            enabled: true
            existingSecret: minecraft-gug-secrets
            secretKey: rcon-password
          memory: 12288M

        mcbackup:
          enabled: true
          pruneBackupDays: 7
          persistence:
            storageClass: truenas-iscsi-hdd
            backupDir:
              enabled: true
              Size: 50Gi

        affinity:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
              - weight: 100
                podAffinityTerm:
                  labelSelector:
                    matchExpressions:
                      - key: app.kubernetes.io/name
                        operator: In
                        values:
                          - minecraft
                  topologyKey: kubernetes.io/hostname

        extraDeploy:
          - |
            apiVersion: bitnami.com/v1alpha1
            kind: SealedSecret
            metadata:
              name: minecraft-gug-secrets
            spec:
              encryptedData:
                {{- range $key, $value := .Values.minecraft.server.gug.secrets }}
                {{ $key }}: {{ splitList "\n" $value | join "" }}
                {{- end }}

  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.minecraft.namespace }}

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
