apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minecraft-mc
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: minecraft
  source:
    repoURL: https://itzg.github.io/minecraft-server-charts
    targetRevision: 4.26.1
    chart: minecraft
    helm:
      valuesObject:
        serviceAnnotations:
          mc-router.itzg.me/externalServerName: "mc.picori.ca"
        workloadAsStatefulSet: true
        strategyType: RollingUpdate
        persistence:
          storageClass: longhorn
          dataDir:
            enabled: true
            Size: 20Gi
        resources:
          requests:
            cpu: 6
            memory: 16Gi
          limits:
            cpu: 10
            memory: 16Gi
        minecraftServer:
          eula: true
          type: FABRIC
          version: "1.21.4"
          difficulty: normal
          whitelist: {{ join "," .Values.minecraft.server.mc.whitelist }}
          ops: {{ join "," .Values.minecraft.server.mc.ops }}
          maxPlayers: 10
          allowNether: true
          announcePlayerAchievements: true
          spawnProtection: 0
          viewDistance: 32
          motd: "マイクラへようこそ！"
          icon: "http://0x0.st/8e8Y.png"
          rcon:
            enabled: false
          memory: 15360M

          extraPorts:
            - name: voice-chat
              containerPort: 24454
              protocol: UDP
              service:
                enabled: true
                embedded: false
                annotations:
                  metallb.universe.tf/allow-shared-ip: {{ .Values.metallb.ipSharingKey }}
                type: LoadBalancer
                port: 24454

        mcbackup:
          enabled: false
        affinity:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
              - weight: 100
                podAffinityTerm:
                  labelSelector:
                    matchExpressions:
                      - key: app.kubernetes.io/name
                        operator: In
                        values:
                          - minecraft
                  topologyKey: kubernetes.io/hostname

        extraVolumes:
          - volumes:
              - name: voice-chat-config
                configMap:
                  name: minecraft-mc-voice-chat-config
            volumeMounts:
              - name: voice-chat-config
                mountPath: /data/config/voicechat/voicechart-server.properties
                subPath: voicechart-server.properties

        extraDeploy:
          - |
            apiVersion: v1
            kind: ConfigMap
            metadata:
              name: minecraft-mc-voice-chat-config
            data:
              voicechart-server.properties: |
                port=24454
                bind_address=
                max_voice_distance=48.0
                crouch_distance_multiplier=1.0
                whisper_distance_multiplier=0.5
                codec=VOIP
                mtu_size=1024
                keep_alive=1000
                enable_groups=true
                voice_host=mc.picori.ca
                allow_recording=true
                spectator_interaction=false
                spectator_player_possession=false
                force_voice_chat=false
                login_timeout=10000
                broadcast_range=-1.0
                allow_pings=true
                use_natives=true

  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.minecraft.namespace }}

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
