apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minecraft-carpg
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: minecraft
  source:
    repoURL: https://itzg.github.io/minecraft-server-charts
    targetRevision: 5.1.1
    chart: minecraft
    helm:
      valuesObject:
        replicaCount: 0
        initContainers:
          - name: pause-for-setup
            image: busybox
            command:
              - sh
              - -c
              - |
                while [ ! -f /data/setup-complete ]; do
                  echo "Waiting for /data/setup-complete to be created..."
                  sleep 5
                done
            securityContext:
              runAsUser: 0
              runAsGroup: 0
              runAsNonRoot: false
            volumeMounts:
              - name: datadir
                mountPath: /data

        livenessProbe:
          initialDelaySeconds: 120
          failureThreshold: 40

        serviceAnnotations:
          mc-router.itzg.me/externalServerName: "carpg.d3adb5.ca"
        workloadAsStatefulSet: true
        strategyType: RollingUpdate
        persistence:
          storageClass: longhorn
          dataDir:
            enabled: true
            Size: 20Gi
        resources:
          requests:
            cpu: 2
            memory: 10Gi
          limits:
            memory: 10Gi
        extraEnv:
          USE_MEOWICE_FLAGS: "true"
        minecraftServer:
          eula: true
          type: FORGE
          version: "1.19.2"
          difficulty: easy
          maxTickTime: -1
          whitelist: {{ join "," .Values.minecraft.server.carpg.whitelist }}
          ops: {{ join "," .Values.minecraft.server.carpg.ops }}
          maxPlayers: 16
          allowNether: true
          announcePlayerAchievements: true
          spawnProtection: 0
          viewDistance: 20
          motd: "Once upon a time, there was a beaver..."
          rcon:
            enabled: true
            existingSecret: minecraft-carpg-secrets
            secretKey: rcon-password
          memory: 8192M
          overrideServerProperties: false

        mcbackup:
          enabled: true
          pruneBackupDays: 7
          persistence:
            storageClass: truenas-iscsi-hdd
            backupDir:
              enabled: true
              Size: 50Gi

        affinity:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
              - weight: 100
                podAffinityTerm:
                  labelSelector:
                    matchExpressions:
                      - key: app.kubernetes.io/name
                        operator: In
                        values:
                          - minecraft
                  topologyKey: kubernetes.io/hostname

        extraDeploy:
          - |
            apiVersion: bitnami.com/v1alpha1
            kind: SealedSecret
            metadata:
              name: minecraft-carpg-secrets
            spec:
              encryptedData:
                {{- range $key, $value := .Values.minecraft.server.carpg.secrets }}
                {{ $key }}: {{ splitList "\n" $value | join "" }}
                {{- end }}

  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.minecraft.namespace }}

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
