apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-hdd
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: "Delete"
volumeBindingMode: "Immediate"
parameters:
  numberOfReplicas: "1"
  staleReplicaTimeout: "2880"
  dataLocality: best-effort
  fsType: ext4
  migratable: "false"
  diskSelector: hdd
