apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: victoria-logs
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: monitoring

  sources:
    - repoURL: https://oauth2-proxy.github.io/manifests
      targetRevision: 10.7.0
      chart: oauth2-proxy

      helm:
        valuesObject:
          config:
            existingSecret: victoria-logs-oidc-secrets

            configFile: |-
              email_domains = ["*"]
              provider = "keycloak-oidc"
              oidc_issuer_url = "https://id.d3adb5.ca/realms/core"
              redirect_url = "https://logs.d3adb5.ca/oauth2/callback"
              code_challenge_method = "S256"
              allowed_groups = ["/VictoriaLogs"]
              upstreams = [ "static://202" ]
              reverse_proxy = true
              skip_provider_button = true

          metrics:
            serviceMonitor:
              enabled: true

          ingress:
            enabled: true
            className: traefik
            hosts:
              - "logs.d3adb5.ca"
            path: /oauth2
            tls:
              - hosts:
                  - "logs.d3adb5.ca"
                secretName: logs-tls

    - repoURL: https://victoriametrics.github.io/helm-charts
      targetRevision: 0.13.9
      chart: victoria-logs-single

      helm:
        valuesObject:
          server:
            fullnameOverride: victoria-logs

            retentionPeriod: 1y
            retentionDiskSpaceUsage: 40GiB

            persistentVolume:
              enabled: true
              storageClassName: truenas-iscsi-hdd
              size: 50Gi

            resources:
              limits:
                memory: 1Gi
              requests:
                cpu: 100m
                memory: 512Mi

            serviceMonitor:
              enabled: true

            ingress:
              enabled: true
              ingressClassName: traefik
              annotations:
                cert-manager.io/cluster-issuer: letsencrypt
                traefik.ingress.kubernetes.io/router.middlewares: "{{ .Values.monitoring.namespace }}-victoria-logs-oauth2-proxy@kubernetescrd"
              hosts:
                - name: logs.d3adb5.ca
                  path:
                    - /
                  port: http
              tls:
                - secretName: logs-tls
                  hosts:
                    - logs.d3adb5.ca

    - repoURL: https://victoriametrics.github.io/helm-charts
      targetRevision: 0.3.7
      chart: victoria-logs-collector

      helm:
        valuesObject:
          fullnameOverride: victoria-logs-collector

          remoteWrite:
            - url: http://victoria-logs.{{ .Values.monitoring.namespace }}.svc.cluster.local:9428

          tolerations:
            - effect: NoSchedule
              operator: Exists

          podMonitor:
            enabled: true

          resources:
            limits:
              memory: 256Mi
            requests:
              cpu: 50m
              memory: 128Mi

  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.monitoring.namespace }}

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
