apiVersion: operator.tigera.io/v1
kind: Installation
metadata:
  name: default
spec:
  calicoNetwork:
    linuxDataplane: BPF
    ipPools:
      - name: default-ipv4-ippool
        allowedUses:
          - Workload
          - Tunnel
        assignmentMode: Automatic
        disableBGPExport: false
        disableNewAllocations: false
        blockSize: 22
        cidr: 10.244.0.0/16
        encapsulation: IPIP
        natOutgoing: Enabled
        nodeSelector: all()

      - name: default-ipv6-ippool
        allowedUses:
          - Workload
          - Tunnel
        assignmentMode: Automatic
        disableBGPExport: false
        disableNewAllocations: false
        blockSize: 112
        cidr: 2001:db8:1::/64
        encapsulation: None
        natOutgoing: Enabled
        nodeSelector: all()
