apiVersion: operator.tigera.io/v1
kind: Installation
metadata:
  name: default
spec:
  # Setting the ports makes the operator enable prometheus reporting in
  # Felix and Typha; the Services and ServiceMonitors live in metrics.yaml.
  nodeMetricsPort: 9091
  typhaMetricsPort: 9093
  calicoNetwork:
    linuxDataplane: BPF
    ipPools:
      - name: default-ipv4-ippool
        allowedUses:
          - Workload
          - Tunnel
        assignmentMode: Automatic
        disableBGPExport: false
        disableNewAllocations: false
        blockSize: 22
        cidr: 10.244.0.0/16
        encapsulation: None
        natOutgoing: Enabled
        nodeSelector: all()
