apiVersion: operator.tigera.io/v1
kind: Installation
metadata:
  name: default
spec:
  calicoNetwork:
    linuxDataplane: BPF
    ipPools:
      - name: default-ipv4-ippool
        allowedUses:
          - Workload
          - Tunnel
        assignmentMode: Automatic
        disableBGPExport: false
        disableNewAllocations: false
        blockSize: 22
        cidr: 10.244.0.0/16
        encapsulation: VXLANCrossSubnet
        natOutgoing: Enabled
        nodeSelector: all()
