apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: cert-manager
spec:
  description: Certificate management for Kubernetes

  sourceRepos:
    - https://charts.jetstack.io
    - {{ .Values.repository.homelab.url }}

  destinations:
    - namespace: {{ .Values.certManager.namespace }}
      server: https://kubernetes.default.svc
    - namespace: kube-system
      server: https://kubernetes.default.svc

  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
    - group: cert-manager.io
      kind: ClusterIssuer
