apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: ingress-nginx
spec:
  description: Ingress NGINX controller

  sourceRepos:
    - https://kubernetes.github.io/ingress-nginx

  destinations:
    - namespace: {{ .Values.ingress.namespace }}
      server: https://kubernetes.default.svc

  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
    - group: networking.k8s.io
      kind: IngressClass
