apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: keycloak
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Keycloak instances

  sourceRepos:
    - {{ .Values.repository.homelab.url }}

  destinations:
    - namespace: keycloak
      server: https://kubernetes.default.svc

  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
