apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: longhorn
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Replicated local storage on Kubernetes

  sourceRepos:
    - https://charts.longhorn.io
    - https://oauth2-proxy.github.io/manifests
    - {{ .Values.repository.homelab.url }}

  destinations:
    - namespace: {{ .Values.longhorn.namespace }}
      server: https://kubernetes.default.svc

  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
    - group: storage.k8s.io
      kind: StorageClass
    - group: scheduling.k8s.io
      kind: PriorityClass
