apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: metallb
spec:
  description: Load balancers for bare metal Kubernetes

  sourceRepos:
    - https://metallb.github.io/metallb
    - {{ .Values.repository.homelab.url }}

  destinations:
    - namespace: {{ .Values.metallb.namespace }}
      server: https://kubernetes.default.svc

  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
