apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: monitoring
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Applications enabling monitoring and alerting

  sourceRepos:
    - ghcr.io/prometheus-community/charts
    - https://oauth2-proxy.github.io/manifests
    - {{ .Values.repository.homelab.url }}

  destinations:
    - namespace: {{ .Values.monitoring.namespace }}
      server: https://kubernetes.default.svc
    - namespace: kube-system
      server: https://kubernetes.default.svc

  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
