apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: operators
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Operators, including those managed by OLM

  sourceRepos:
    - {{ .Values.repository.url }}
    - https://github.com/operator-framework/operator-lifecycle-manager

  destinations:
    - namespace: {{ .Values.operators.olmNamespace }}
      server: https://kubernetes.default.svc
    - namespace: {{ .Values.operators.namespace }}
      server: https://kubernetes.default.svc
    - namespace: {{ .Values.monitoring.namespace }}
      server: https://kubernetes.default.svc
    - namespace: keycloak
      server: https://kubernetes.default.svc

  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
    - group: operators.coreos.com
      kind: OLMConfig
