apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: sealed-secrets
spec:
  description: One-way encrypted secrets, by Bitnami

  sourceRepos:
    - https://bitnami-labs.github.io/sealed-secrets

  destinations:
    - namespace: {{ .Values.sealedSecrets.namespace }}
      server: https://kubernetes.default.svc

  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
