apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: ingress-nginx

  source:
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: 4.13.3
    chart: ingress-nginx

    helm:
      valuesObject:
        controller:
          replicaCount: 3
          allowSnippetAnnotations: true
          config:
            annotations-risk-level: Critical
            strict-validate-path-type: false
          service:
            annotations:
              metallb.universe.tf/allow-shared-ip: {{ .Values.metallb.ipSharingKey }}
          topologySpreadConstraints:
            - maxSkew: 1
              topologyKey: kubernetes.io/hostname
              whenUnsatisfiable: ScheduleAnyway
              nodeTaintsPolicy: Honor
              labelSelector:
                matchLabels:
                  app.kubernetes.io/name: ingress-nginx
                  app.kubernetes.io/component: controller

  destination:
    namespace: {{ .Values.ingress.namespace }}
    server: https://kubernetes.default.svc

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
