name: Docker

on:
  push:
    branches:
      - master
    paths:
      - "images/**"

jobs:
  build-matrix:
    name: Build Matrix
    runs-on: ubuntu-latest

    outputs:
      matrix: ${{ steps.jsonmatrix.outputs.matrix }}

    steps:
      - uses: actions/checkout@v4
      - id: jsonmatrix
        run: |
          find images -maxdepth 2 -type f -name Dockerfile -exec dirname {} \; \
            | xargs -L 1 basename | jq -cR '{image:[.,inputs]}' > matrix.json
          echo "matrix=$(cat matrix.json)" >> "$GITHUB_OUTPUT"

  build-image:
    name: Build & Push
    runs-on: ubuntu-latest

    needs: build-matrix
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.build-matrix.outputs.matrix) }}

    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v6
        with:
          context: images/${{ matrix.image }}
          tags: ghcr.io/${{ github.actor }}/${{ matrix.image }}:latest
          load: true

      - uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: ghcr.io/${{ github.repository_owner }}/${{ matrix.image }}:latest
          severity: CRITICAL,HIGH
          ignore-unfixed: false
          exit-code: "1"

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v6
        with:
          context: images/${{ matrix.image }}
          tags: ghcr.io/${{ github.repository_owner }}/${{ matrix.image }}:latest
          push: true
