name: Helm

on:
  push:
    branches:
      - master
  pull_request: {}

jobs:
  lint:
    name: Lint App-of-Apps
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: azure/setup-helm@v4
      - run: helm lint argo/app-of-apps
