{{- range .Values.denyAll.namespaces }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-all
  namespace: {{ . }}
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
  ingress: []
  egress:
    - to:
        - ipBlock:
            cidr: 10.96.0.10/32
        - ipBlock:
            cidr: 169.254.169.254/32
      ports:
        - port: 53
          protocol: UDP
{{- end }}
