---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: transmission-allow-all-ingress
  namespace: media
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: transmission
  policyTypes:
    - Ingress
  ingress:
    - {}
